### ISSUE TITLE
Odd ghost mask

### ISSUE THREAD

**Issue by dpoincelot** [igorescobar/jQuery-Mask-Plugin#290]
Hi,
Thank you for a great plugin! Much appreciated. Can you please look at this fiddler, https://jsfiddle.net/dpoincelot/2o2v2n8r/

I have several masks in there. All of them work. The user can add numeric phone numbers, as well as toll free numbers with letters. I am having 1 issue. If you enter a number like (333) 333-3333 and click back into the area code to change it like this (222) 333-3333 the mask breaks and creates an entire new mask.
Thanks!

**Comment by igorescobar** [comment]
Very messy code but I think the problem was with your "A" pattern:
https://jsfiddle.net/2o2v2n8r/3/

Looks better now?

**Comment by igorescobar** [comment]
Latest:
https://jsfiddle.net/2o2v2n8r/4/

**Comment by dpoincelot** [comment]
Thanks for the quick response. Sorry about the mess, I pasted in you min code, but should have called it from your site. The code still doesn't work.

I type in (222)-222-2222. I click into (222) and try to change it to (333), but it turns into (323).

**Comment by igorescobar** [comment]
When you select 3 chars at the same time and digit only one jquery mask will change character's position.

If you type:
(222) 222-2222, select "222" and paste 333 the result will be: (333) 222-2222
But if you (222) 222-2222, select "222" and type "3", the result will be: "(322) 222-22" witch is the expected result. The problem is that the cursor will be changed to POS + 1, ex: "(32->|<-2) 222-22" and if you start type right now and output could be something unexpected... I don't know if I can do much better than that without breaking another things... but... PR as appreciated...

**Comment by dpoincelot** [comment]
OK, appreciate you taking a look! I will give it some thought and let you know if I'm able to adjust.
