### ISSUE TITLE
Length limitation

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [igorescobar/jQuery-Mask-Plugin#296]
Hello! It's more a question than an issue.

In v.1.6.4 if you keep pressed a number, until it reaches the limit of mask (5 for "99999" mask), the input automatically crop into 5th number. 

In the last release this behavior it's no longer available. There is a reason for this?

**Comment by HASSED** [comment]
Hello, I have a possible problem in this regard too, waiting for the answer.

**Comment by igorescobar** [comment]
Yes, because what the plugin did was simple add a maxlength attribute. You can simply add it on your own, that's why we removed it.

**Comment by HASSED** [comment]
When I use a mask normally only applied even I reporting a maxlength greater than the configured mask, for example, my mask is 0.00 with a maxlength 9, if I maintain a precionada key will be added to the field 9 characters, however, the drop will only be kept 3, ie, the corresponding mask 0.00. Now the problem is when I use the recursive option (#. ## 0,00), if I put a maxlength 9 at the end is 00.000,00, but maintaining a precionada key is 0,000,000.00 . As I understand it, it adds the mask on the 9 digits informed, not removing when the maxlength is exceeded, I see, the mask is told in maxlength, but when used the recursive, not. This is a bug or an improvement?

Here's an example applied to http://plnkr.co/Yji9m3

**Comment by igorescobar** [comment]
@HASSED I truly recommend you to use a money/currency plugin for solve monetary situations.

**Comment by HASSED** [comment]
Igor understand, in this case, I used masking money to exemplify, but the mentioned case occurs every time you use the recursive mode. Washing into account the premise of your plugin, which considers the Shade in maxlength and comes when the user maintains a precionada key, so it should also run recursively. I believe that could be checked at the time of application of the mask, which is the recursive mode is active, check if there is a maxlength on the field and remove excess, as is done in the rest. Take a look fondly on this case, I think that would make the most interesting plugin. Thank you.

**Comment by igorescobar** [comment]
@HASSED In my browser when a keep a any key pressed nothing happens... only 1 char is inserted and nothing more... is this an issue with windows or a specific browser?

**Comment by HASSED** [comment]
@igorescobar Sorry, I did not mention this detail. On windows;. (When you hold a precionada key, the character is being repeated in the field to complete the maxlength On Mac and Linux, so tested, does not happen precisely because the character is not repeated testares If the windows in the example. I spent, adding a character at a time, it works perfectly, but he left the precionada key is where the problem occurs, but only if you use the recursive mode.

**Comment by igorescobar** [comment]
So we're basically chasing a problem to the user who wants to screw things up or this is actually a use case?

**Comment by igorescobar** [comment]
I mean.. this is a problem that the "end user" would face, or this is a problem caused by an asshole using the interface? LOL. I'm saying this because I don't really like the idea of adding a "watcher" os something like that... The user who wants to screw things up will probably disable the javascript or populate the field by another ways...

**Comment by HASSED** [comment]
Uhoww spoil? Ever, this is a use case, analyzed by testers and analysts. In my example, is visible the problem, there in plnkr, if you type a character at a time, the final field value is 33333.33, now if I leave the 3 precionado the windows, the final value is 3,333,333.33 the set maxlength is nine and in this case, the field ended up with more than 9 characters, since the mask is counted. For analysts and testrs, this is a mistake so I am suggesting improvement. There really exists cases where the user can fill a field with the same character, then keeping it precionado is the fastest way to fill, such as in a my case, the maxlength is 17.

**Comment by igorescobar** [comment]
I got what you mean but the problem is that the "maxlength" is a browser feature and not a jQuery Mask Feature anymore. 

If you can type more then the defined maxlength of your HTML field your browser is probably creazy, right? 

The "maxlength" feature was removed in 2014 as you can see in our CHANGELOG.md:

```
== v1.8.0 (Oct/17 2014 11:35 -0300 by Igor Escobar) ==
Changes:
removing automatic maxlength support
making a few optimizations to make it faster and retro compatible with other libraries
creating globalOptions to make it more fast and flexible
```

it was removed bacause there is too many cases and possibilities for this feature when you introduce a reverse and optional chars... it ended up being too hard to maintain so I decided to remove the support and let the user (in this case the programmer) decide which maxlength the field should have.

**Comment by igorescobar** [comment]
Anyways... I'm able to test it on Windows, only in Mac and Linux (Ubuntu) you guys could propose a solution to it via PR and I would be more than happy to analize and merge it, sounds good?

**Comment by HASSED** [comment]
Okay, I'll see if I can implement a solution, giving all right, sent to you via PR. thank you @igorescobar
