### ISSUE TITLE
masked element's "change" event ignored when using "reverse" option

### ISSUE THREAD

**Issue by khafancoder** [igorescobar/jQuery-Mask-Plugin#3]
after applying masks which includes separator chars with the reverse option=true, the input's "change" event would not be triggered anymore :

$("#input1").mask("999,999,999",  { reverse: true });
$("#input1").change(function()
{
    alert("value changed");    //ignored
});

**Comment by swimitup** [comment]
Seem to be a quite long this issue has been discovered, but please pay attention to your default value or to the maxlength property of the input.
ex: i had an input for hour (hh:mm) that was receiving 14:00:00 as default value (<input type=text name=blah class="horario" value="14:00:00">... $(".horario").mask("00:00").
the jquery did not trigger if you try to change the hour (13:00) but it will trigger if you change the minutes (14:01). by accident i discovered that somehow the change was not triggered in the masked field because the masked field was returning 00:00 (the last 5 chars), not 15:00 (the 5 firts chars), hence there was no reason for jquery trigger the change in the input...
not sure if it's a bug, but i spend 3h on this. hope it helps somebody else's work.

**Comment by mscarchilli** [comment]
Having this same exact problem in Chrome with v1.13.4. Using jQuery v1.11.0

Usage:
$(".elm").mask("000,000", {reverse: true});

**Comment by odenirdev** [comment]
i have the same problem in jquery v3.5.0 and jquery-mask v1.14.16
