### ISSUE TITLE
Mask hours!

### ISSUE THREAD

**Issue by m4a1fox** [igorescobar/jQuery-Mask-Plugin#315]
Hi! I've the question. I've found, in examples, that I can use plugin to set the time, but, I've some confusing when I try to input the time with PM AM format. My code now
<code>
$('#timepicker').mask('00:00 ZZ', {
        translation: {
            'Z': {
                pattern: /[AM|PM]/, optional: true
            }
        }
    });
</code>

But I can type this data "45:99 AM", which is wrong. How can I fix this problem. Thanks.

**Comment by igorescobar** [comment]
I really recommend you to use a "date/time plugin" to solve that problem. 

But... some considerations about what you're trying to do:

1 - one pattern = one digit. 
2 - you can't represent 2 digits at once. 
3 - the regex is wrong. 
4 - You need to re evaluate your mask as your user types.

But you can do something like that if you only want to guide your user about de AM/PM:

```javascript
$('#timepicker').mask('00:00 ZM', 
    {
      translation: {
        'Z': {
          pattern: /[AP]/
        }
      },
      placeholder: "__:__ AM"
    } 
);
```

If you need to validate date/time accuracy I really recommend you to use a date/time plugin because your code is going to look messy because you will need to change your mask like we do here:

https://gist.github.com/igorescobar/6450250
https://gist.github.com/igorescobar/7355657
http://jsfiddle.net/igorescobar/rtvwfnhh/
