### ISSUE TITLE
Invalid time

### ISSUE THREAD

**Issue by paulomcnally** [igorescobar/jQuery-Mask-Plugin#329]
Time allow invalid times

![Img](http://i.imgur.com/FHLUsHz.png)

**Comment by paulomcnally** [comment]
This is a valid regular expression for time:

    ^([0-9]|0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$

http://rubular.com/r/FrMXGs6pFC

**Comment by igorescobar** [comment]
I don't think you got this plugin :)

**Comment by paulomcnally** [comment]
?

**Comment by paulomcnally** [comment]
i don't understand

**Comment by RedPointMS** [comment]
Igor,

I agree with Paulo. On your demo page the time input doesn't work correctly as per Paulo's screenshot. I discovered the same problem and found this thread.

**Comment by igorescobar** [comment]
Guys,

Please... jQuery Mask is a generic mask plugin. If you want data consistency you need to use it along with a validation plugin like http://formvalidation.io/

All examples in the project's website are only for exemplify how you could use it in order to help your user on how do fill the field.

**Comment by RedPointMS** [comment]
Paoulo,

use the translation option with regex to implement own time validation. Worked for me.

**Comment by paulomcnally** [comment]
@RedPointMS have an example? Thanks

**Comment by RedPointMS** [comment]
I am using slightly customized version for time position rather then clock but I quickly wrote more generic that might work for you (this is 12 hours time format). You might want to experiment with this configuration (HH/MM/SS/MS):
```javascript
$('#field').mask('AB:M0:M0:000', {
        'translation': {
            'A': { pattern: /[0-1]/, optional: true }, //hours - tens position
            'B': { pattern: /[0-2]/, optional: false}, //hours - units position
            'M': { pattern: /[0-5]/, optional: true }, //minutes and seconds - tens position
        }
    });
```

**Comment by RedPointMS** [comment]
I have slightly different field as I am displaying time position rather than the clock. I thought I could create one for you quickly like this:
```javascript
$('#field').mask('AB:M0:M0:000', {
        'translation': {
            'A': { pattern: /[0-1]/, optional: true }, //hours - tens position
            'B': { pattern: /[0-1]/, optional: false}, //hours - units position
            'M': { pattern: /[0-5]/, optional: true }, //minutes and seconds - tens position
        }
    });
```
but the problem is that it still would accept hours like '29' which obviously is not correct. The only way to solve it would be to use callback function on `onKeyPress` event and checking if the number is less than 24. I hope this helps.

**Comment by paulomcnally** [comment]
Thanks @RedPointMS
