### ISSUE TITLE
interval fires every 300ms by default

### ISSUE THREAD

**Issue by Philbob** [igorescobar/jQuery-Mask-Plugin#333]
there is an interval raised at the end of the file 

setInterval(function(){
        if ($.jMaskGlobals.watchDataMask) { $.applyDataMask(); }
    }, globals.watchInterval);

this by default fires every 300ms and the if condiftion eval's to false, meaning that there is an interval firing very 300 ms that essentially serves no purpose.  The condition should probably wrap the interval.

**Comment by igorescobar** [comment]
PR :)

[]'s
Igor

**Comment by Philbob** [comment]
just working on it now :-) , however when trying to write some tests for this i've realised that jMaskGlobals is assigned immediately from globals and directly patches jQuery/Zepto so i can't intercept if before the interval is raised, without first setting a global jquery/zepto param before i've loaded the plugin.

Am i reading that correctly or am i missing something?

**Comment by gunnx** [comment]
+1

**Comment by igorescobar** [comment]
Nowadays interfaces are pretty dynamic and you're constantly loading and modifying things on your DOM structure... With that in mind... The global variable `$.jMaskGlobals.watchDataMask` need to be checked every time in case anything changes on your system otherwise even if you pragmatically change the variable the behaviour will not be attached to the element.
