### ISSUE TITLE
Last character typed outside the mask is registered incorrectly but not shown

### ISSUE THREAD

**Issue by ghost** [igorescobar/jQuery-Mask-Plugin#340]
The last character I type is stored incorrectly but not shown.

E.g.:

```javascript
$('input').mask('99', {
    onChange: function () {
        console.log($('input').val());
    }
});
```

If I then type '123', only '12' is displayed, but '123' is shown by `$('input').val()`.

**Comment by keldar** [comment]
In fact - I don't think this is a problem in vanilla JS - I'm using it with Cordova/jQuery Mobile; I will see if I can narrow down the problem where it's introduced.

**Comment by elijahpaul** [comment]
I'm seeing the same behaviour (Chrome 45.0.2454.85 m / Windows 8.1), except in my case the extra value ('3' from your example) doesn't show in the console.

I'm using the mask in combination with [jQuery Credit Card Validator](https://github.com/PawelDecowski/jQuery-CreditCardValidator/) to show a green tick when the entered credit card number is valid.

e.g. American Express mask.
```
$('#cc_number').mask("0000 000000 00000");
```
If I input the valid test cc value `3782 822463 10005` I see the following:

![inputmask_no_extra](https://cloud.githubusercontent.com/assets/478088/9743981/241d3fc2-5661-11e5-8b77-6fde9267c1f4.png)

However, if I type an extra digit, so `3782 822463 100058`, the extra digit `8` is not shown, but is stored since it breaks cc validation and the green tick disappears.

![inputmask_extra](https://cloud.githubusercontent.com/assets/478088/9744080/b07bb5ca-5661-11e5-95ba-a41e96a669eb.png)

**Comment by igorescobar** [comment]
@elijahpaul I couldn't reproduce it here on Google Chrome (Mac). Maybe some windows user could help me?

**Comment by elijahpaul** [comment]
hey @igorescobar thanks for the update.

I created another fiddle [http://jsfiddle.net/56uscbjv/](http://jsfiddle.net/56uscbjv/) to better demonstrate the issue.

Just paste one of the provided test card numbers and you should get a `Valid Credit Card' msg. Then try typing an extra digit on the end to break the validation. The extra digit isn't displayed, but is still picked up by the validation plugin.

Please do let me know if you don't see this behaviour?

**Comment by igorescobar** [comment]
@elijahpaul now I see what you meant. This is happening because both plugins are running async. jQuery Mask avoid the char being typed but the creditcard plugin captures the char. I don't really know how to solve this... ideas?

**Comment by igorescobar** [comment]
Also have some questions on the mater that if our plugin should really care about those "conflicts".  This looks like a implementation problem of your creditcard plugin. Both plugins are using namespaced events so they need to care about their own events.
