### ISSUE TITLE
Mask with different length copy/paste problem

### ISSUE THREAD

**Issue by coder4u** [igorescobar/jQuery-Mask-Plugin#406]
hello.

Sorry for my english.
I have problem with mask, which is dynamically changed, and may have different length.

More description in fiddle.

http://jsfiddle.net/coder4u/ghdpv9zk/2/

**Comment by igorescobar** [comment]
That is because the mask configured in the fist place is this one: `0000 000000 00000` and when you paste the second creditcard number the number is too large for the mask `0000 000000 00000` and then the last number is removed. Its not a bug this is how it is supposed to work. You must improve your logic in order to avoid this if this is a real use case.

**Comment by coder4u** [comment]
Thank you for response.
I think that this is common use case for american payment forms. And i dont now can i change logic for this.
I could use a plugin for payment forms (ex. http://stripe.github.io/jquery.payment/example/), but chose a more easy and simple solution - jQuery-Mask-Plugin.
