### ISSUE TITLE
How to properly support screen readers?

### ISSUE THREAD

**Issue by SevenHong** [igorescobar/jQuery-Mask-Plugin#413]
Tried to find a better place to ask, but could only ask here..

Here in my team we are developing pages with accessibility support. I ran JAWS(a screen reader) and randomly typed on forms, then I heard characters both allowed by the rules and blocked by the rules. For example:

1. run JAWS & go to mask plugin's [project page](https://igorescobar.github.io/jQuery-Mask-Plugin/)
2. on "Date" input form, if I type `12ab12` I see `12/12` but I hear `one two a b one two`. I imagine that if a blind user hears `one two a b one two` then he/she may assume that there is string `12ab12` in the Date input form, which might cause confusion.

Just want to know if mask plugin has better support on screen reader than this? Based on project page and github readme.md I guess this plugin doesn't support screen reader yet though.

**Comment by igorescobar** [comment]
You can help to make it compatible, just tell me why this is happening and
I will see that I can do to help.

Regards,
Igor Escobar

*Software Engineer*
+ http://blog.igorescobar.com
+ http://www.igorescobar.com
+ @igorescobar <http://www.twitter.com/igorescobar>

**Comment by Marciobds** [comment]
Hi,

as far as I know this happens because JAWS reads all that the user inputs, so I guess there is nothing that can be done about that.

But if you want the user to know that he should not input letters, that is a feedback that could be given by an alert message. I know this is a pretty ugly solution but alerts are accessible, we just need to be careful not to make it too much intrusive for the user.

Other thing that is a MUST for accessibility is the label that describes the field, you can and should use it to inform the user the format of what he should type. For example if you want the user to input a date format 2016-05-17 you should inform him that the format is XXXX-XX-XX and this could be done on the label. You should also inform that he is to type only numbers. Just be careful not to put too much text.

After validation or during the typing if the user types [a-z] or other characters not allowed, just inform him that it is not possible to type such characters.

If you think that i will break your layout putting this information on the label, just do like bootstrap on the sr-only information, thei hide the information on the layout, but it is still being displayed on the page, so the screen reader can access it.

Please feel free to contact me if need any help, if it is something I know I will be very pleased to help.

Regards,

Márcio Bortolini

**Comment by igorescobar** [comment]
@Marciobds I think you can plug that functionality to those fields without having to add it to our core.

**Comment by Marciobds** [comment]
As I stated that's what @SevenHong has to do, the mask doesn't need to change, just the feedback given to the user, and that in my opinion can and should ben done using HTML, on the label of the field and afterwards on validation messages if necessary.

**Comment by igorescobar** [comment]
@Marciobds @SevenHong If you guys want to start a PR suggesting what you guys think that needs to change I would be more than happy to assist you in order to get the better solution.

**Comment by Marciobds** [comment]
@igorescobar Na verdade somente respondi para tentar ajudar ele com acessibilidade, sugeri algumas coisas que ele pode fazer no site para ser mais acessível, mas não vejo necessidade de transformações no plugin..

**Comment by igorescobar** [comment]
@Marciobds Okey then ;)
