### ISSUE TITLE
Not working at all on Safari

### ISSUE THREAD

**Issue by nooch** [igorescobar/jQuery-Mask-Plugin#456]

**Comment by tiesont** [comment]
"Not working on Safari" is no different than saying "not working on IE" - you need to be more specific (OS and/or browser version, etc.), not to mention defining what "not working" even means. Console errors? Unexpected behavior?

**Comment by nooch** [comment]
Appreciate the quick response!  It was "not working" in that the mask was
not being applied whatsoever as if the plugin wasn't used at all.  I
mentioned Safari v9.1.1.  Expected behavior would have been the normal mask
being applied.

But all moot points - it ended up being caused by an issue with another
plugin (Bootstrap Datetime picker) because of the format of a date that it
didn't like.  Not sure why it only caused an issue in Safari, but it did.
I changed the date format when calling the datetime picker (which was a
different input altogether from the input that had the input-mask applied)
and now all the input masks are working as expected.

Sorry for the preemptive post here!

**Comment by tiesont** [comment]
Are you using something along the lines of `<input type="date" />`? If so, and if Webkit (Safari's rendering engine) shares it's date input support with Blink (Chrome's "new" rendering engine), then it wants the date format to be `yyyy-MM-dd` - anything else results in the value not being bound.

It's worth mentioning that you shouldn't be using a mask (or date plugin, for that matter) if the browser you're targeting has native date input support - it already is masking the input. You would normally treat the mask and/or plugin as a polyfill, like so (assuming Modernizr is available):
```
if (!Modernizr.inputtypes.date) {
    $('.date').datepicker({
        /* your options */
    });
}
```
If you're using a plugin because you want consistency with the rest of the Bootstrap styling, use an `<input type="text" />` instead.
