### ISSUE TITLE
URL stuff in the Comments

### ISSUE THREAD

**Issue by robmburke** [igorescobar/jQuery-Mask-Plugin#616]
The comment section does not direct the developer to this GitHub page. Would be nice to have it there instead of having to open up Bower management in Visual Studio to see where this repository is.

Also, the link to UMD is bad: in the comments.
https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

Don't know if you want to address this at some point, but just pointing it out.

**Comment by igorescobar** [comment]
@robmburke I got the UMD part and already fixed it. But I didn't get the first part. Can you explain a little better?

**Comment by robmburke** [comment]
There is nothing in the JavaScript file that directs a developer to this GitHub page. I can look at the Bower entry and find the URL to here but it's generally easier to just open up the JS file and see a link somewhere in the comments of the source file.  There are two links to your blog but not one to the GitHub page. and looking at it again there is a place that says to report bugs to your blog but it would make sense to have that direct here to GitHub since you also have a blog link next to your name copyright info literally two lines down.

**Comment by igorescobar** [comment]
Hum... you are right and I didn't notice that :-)

I realized that the `.min.js` file does have it.
<img width="545" alt="screen shot 2017-10-17 at 14 15 06" src="https://user-images.githubusercontent.com/24032/31666891-be25aa94-b345-11e7-8115-a9928b0c6bb2.png">

But the `.js` file doesn't.

This will be fixed in the next release ok? thanks
