### ISSUE TITLE
data-mask doesn't work

### ISSUE THREAD

**Issue by PunkHaz4rd** [igorescobar/jQuery-Mask-Plugin#617]
Here's the jsfiddle you provided, with the problem I encounter:

http://jsfiddle.net/LmhLs9Lt/7/

**Comment by igorescobar** [comment]
@PunkHaz4rd The problem is this:

In this jsfiddle you are including the jquery mask before your HTML is loaded so if you don't include your js files as the last thing to load on your website (which is a best practice) by the time the code runs no `data-mask` will be found. So you have two options here.

1 - You move all your js files to the end of your HTML file.
2 - You turn on the `$.jMaskGlobals.watchDataMask = true;` options as stated on our documentation (http://jsfiddle.net/LmhLs9Lt/8/).

Thanks!
