### ISSUE TITLE
Active placeholder when typing

### ISSUE THREAD

**Issue by Sogl** [igorescobar/jQuery-Mask-Plugin#633]
Hello!

I didn't find any similar behavior in the demos either in the documentation:
![1](https://user-images.githubusercontent.com/7556290/33630743-7673b600-da19-11e7-8753-70e816c19867.gif)

How to turn it on?

**Comment by pyetrosafe** [comment]
@Sogl 
I think your issue is similar to this: #631

**Comment by pyetrosafe** [comment]
I do not think this is possible. The placeholder used in this plugin is the HTML 5 native placeholder, so to use an active placeholder as your example, you need to make script for it.

**Comment by igorescobar** [comment]
https://github.com/igorescobar/jQuery-Mask-Plugin#problems-or-questions

**Comment by Sogl** [comment]
@igorescobar Issue closed...so what's the solution?
If you mean this comment:
https://github.com/igorescobar/jQuery-Mask-Plugin/issues/450#issuecomment-253225719

I use `input type=text`.

**Comment by igorescobar** [comment]
I'm sorry @Sogl. To summarize this for you: This is a feature that I don't intend to implement. Why? Because the amount of code necessary to make it work across all features of this plugin (and to make it work on all browsers that we support) would make this plugin considerably heavier. If you think this is a mandatory feature for your user to be able to input things in your form you can always try to use another plugin available out there.

**Comment by igorescobar** [comment]
Also... you can always check related thread:
#409 #198 #80 #92 #110 #11

**Comment by Saghachi** [comment]
still hope a dynamic placeholder be added to this script while keeping the lightweight of it :)
